const cityOptions = ['投保示列首页', '电子收款凭证', '收款凭证', '其他生效规则','投保示列首页1', '电子收款凭证2', '收款凭证3', '其他生效规则4'];
var vm = new Vue({
    el:"#app",
    data:{
        //鼠标移上菜单变色标识
        flag2:"2000",
        //显示按钮标识
        flag3:true,
        //点击修改显示按钮标识
        flag4:true,
        //列表复选框标识
        checked:false,
        //新增模块
        checkedCities1: [],
        cities: cityOptions,
        searchContent:"",
        //模块列表
        'meList':[
            {
                'moduleid':'模块id',
                'modulename':'模块名称',
                "checked":false,
                'elementList':[
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    },
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    },
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    },
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    },
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    },
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    },
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    },
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    }

                ]
            },
            {
                'moduleid':'模块id',
                'modulename':'模块名称',
                "checked":false,
                'elementList':[
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    },
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    },
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    },
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    },
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    },
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    },
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    },
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    }
                ]
            },
            {
                'moduleid':'模块id',
                'modulename':'模块名称',
                "checked":false,
                'elementList':[
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    },
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    },
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    },
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    },
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    },
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    },
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    },
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    }
                ]
            },
            {
                'moduleid':'模块id',
                'modulename':'模块名称',
                "checked":false,
                'elementList':[
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    },
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    },
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    },
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    },
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    },
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    },
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    },
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    }
                ]
            },
            {
                'moduleid':'模块id',
                'modulename':'模块名称',
                "checked":false,
                'elementList':[
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    },
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    },
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    },
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    },
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    },
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    },
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    },
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    }
                ]
            },
            {
                'moduleid':'模块id',
                'modulename':'模块名称',
                "checked":false,
                'elementList':[
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    },
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    },
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    },
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    },
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    },
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    },
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    },
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    }
                ]
            },
            {
                'moduleid':'模块id',
                'modulename':'模块名称',
                "checked":false,
                'elementList':[
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    },
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    },
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    },
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    },
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    },
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    },
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    },
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    }
                ]
            },
            {
                'moduleid':'模块id',
                'modulename':'模块名称',
                "checked":false,
                'elementList':[
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    },
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    },
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    },
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    },
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    },
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    },
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    },
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    }
                ]
            },
            {
                'moduleid':'模块id',
                'modulename':'模块名称',
                "checked":false,
                'elementList':[
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    },
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    },
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    },
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    },
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    },
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    },
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    },
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    }
                ]
            },
            {
                'moduleid':'模块id',
                'modulename':'模块名称',
                "checked":false,
                'elementList':[
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    },
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    },
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    },
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    },
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    },
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    },
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    },
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    }
                ]
            },
            {
                'moduleid':'模块id',
                'modulename':'模块名称',
                "checked":false,
                'elementList':[
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    },
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    },
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    },
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    },
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    },
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    },
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    },
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    }
                ]
            },
            {
                'moduleid':'模块id',
                'modulename':'模块名称',
                "checked":false,
                'elementList':[
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    },
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    },
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    },
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    },
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    },
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    },
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    },
                    {
                        'elementid':'要素id',
                        'elementname':'要素名称'
                    }
                ]
            }
        ],
        elementList:[
            {
                'id':'id',
                'area':'区域',
                'insuranceid':'险种id',
                'moduleid':'模块id',
                'elementid':'要素id',
                'elementdetail':'要素释义',
                'printshow':'打印显示',
                'commonrule':'通用规则',
                'appendinsuranceids':'附加险id',
                'chengbaorule':'承保规则',
                'hebaorule':'核保规则',
                'insurancerule':'保险条款',
                'otherrule':'其他规则',
                'sysrecord':'系统记录',
                'sysproduce':'系统生成',
                'existcheck':'存在性审核',
                'okcheck':'正确性审核',
                'FFcheck':'FF系统校验',
                'yingxiangcheck':'投保单影像校验',
                'checkstandard':'校验标准',
                'remarks':'备注',
                'versionid':'版本号',
                'elementname':'要素名称',
                'percent':80   //80以下标黄 
            },
            {
                'id':'id',
                'area':'区域',
                'insuranceid':'险种id',
                'moduleid':'模块id',
                'elementid':'要素id',
                'elementdetail':'要素释义',
                'printshow':'打印显示',
                'commonrule':'通用规则',
                'appendinsuranceids':'附加险id',
                'chengbaorule':'承保规则',
                'hebaorule':'核保规则',
                'insurancerule':'保险条款',
                'otherrule':'其他规则',
                'sysrecord':'系统记录',
                'sysproduce':'系统生成',
                'existcheck':'存在性审核',
                'okcheck':'正确性审核',
                'FFcheck':'FF系统校验',
                'yingxiangcheck':'投保单影像校验',
                'checkstandard':'校验标准',
                'remarks':'备注',
                'versionid':'版本号',
                'elementname':'要素名称',
                'percent':79  //80以下标黄  
            },
            {
                'id':'id',
                'area':'区域',
                'insuranceid':'险种id',
                'moduleid':'模块id',
                'elementid':'要素id',
                'elementdetail':'要素释义',
                'printshow':'打印显示',
                'commonrule':'通用规则',
                'appendinsuranceids':'附加险id',
                'chengbaorule':'承保规则',
                'hebaorule':'核保规则',
                'insurancerule':'保险条款',
                'otherrule':'其他规则',
                'sysrecord':'系统记录',
                'sysproduce':'系统生成',
                'existcheck':'存在性审核',
                'okcheck':'正确性审核',
                'FFcheck':'FF系统校验',
                'yingxiangcheck':'投保单影像校验',
                'checkstandard':'校验标准',
                'remarks':'备注',
                'versionid':'版本号',
                'elementname':'要素名称',
                'percent':87   //80以下标黄  
            },
            {
                'id':'id',
                'area':'区域',
                'insuranceid':'险种id',
                'moduleid':'模块id',
                'elementid':'要素id',
                'elementdetail':'要素释义',
                'printshow':'打印显示',
                'commonrule':'通用规则',
                'appendinsuranceids':'附加险id',
                'chengbaorule':'承保规则',
                'hebaorule':'核保规则',
                'insurancerule':'保险条款',
                'otherrule':'其他规则',
                'sysrecord':'系统记录',
                'sysproduce':'系统生成',
                'existcheck':'存在性审核',
                'okcheck':'正确性审核',
                'FFcheck':'FF系统校验',
                'yingxiangcheck':'投保单影像校验',
                'checkstandard':'校验标准',
                'remarks':'备注',
                'versionid':'版本号',
                'elementname':'要素名称',
                'percent':40   //80以下标黄  
            },
            {
                'id':'id',
                'area':'区域',
                'insuranceid':'险种id',
                'moduleid':'模块id',
                'elementid':'要素id',
                'elementdetail':'要素释义',
                'printshow':'打印显示',
                'commonrule':'通用规则',
                'appendinsuranceids':'附加险id',
                'chengbaorule':'承保规则',
                'hebaorule':'核保规则',
                'insurancerule':'保险条款',
                'otherrule':'其他规则',
                'sysrecord':'系统记录',
                'sysproduce':'系统生成',
                'existcheck':'存在性审核',
                'okcheck':'正确性审核',
                'FFcheck':'FF系统校验',
                'yingxiangcheck':'投保单影像校验',
                'checkstandard':'校验标准',
                'remarks':'备注',
                'versionid':'版本号',
                'elementname':'要素名称',
                'percent':78   //80以下标黄   
            },
            {
                'id':'id',
                'area':'区域',
                'insuranceid':'险种id',
                'moduleid':'模块id',
                'elementid':'要素id',
                'elementdetail':'要素释义',
                'printshow':'打印显示',
                'commonrule':'通用规则',
                'appendinsuranceids':'附加险id',
                'chengbaorule':'承保规则',
                'hebaorule':'核保规则',
                'insurancerule':'保险条款',
                'otherrule':'其他规则',
                'sysrecord':'系统记录',
                'sysproduce':'系统生成',
                'existcheck':'存在性审核',
                'okcheck':'正确性审核',
                'FFcheck':'FF系统校验',
                'yingxiangcheck':'投保单影像校验',
                'checkstandard':'校验标准',
                'remarks':'备注',
                'versionid':'版本号',
                'elementname':'要素名称',
                'percent':78   //80以下标黄 
            },
            {
                'id':'id',
                'area':'区域',
                'insuranceid':'险种id',
                'moduleid':'模块id',
                'elementid':'要素id',
                'elementdetail':'要素释义',
                'printshow':'打印显示',
                'commonrule':'通用规则',
                'appendinsuranceids':'附加险id',
                'chengbaorule':'承保规则',
                'hebaorule':'核保规则',
                'insurancerule':'保险条款',
                'otherrule':'其他规则',
                'sysrecord':'系统记录',
                'sysproduce':'系统生成',
                'existcheck':'存在性审核',
                'okcheck':'正确性审核',
                'FFcheck':'FF系统校验',
                'yingxiangcheck':'投保单影像校验',
                'checkstandard':'校验标准',
                'remarks':'备注',
                'versionid':'版本号',
                'elementname':'要素名称',
                'percent':88   //80以下标黄 
            },
            {
                'id':'id',
                'area':'区域',
                'insuranceid':'险种id',
                'moduleid':'模块id',
                'elementid':'要素id',
                'elementdetail':'要素释义',
                'printshow':'打印显示',
                'commonrule':'通用规则',
                'appendinsuranceids':'附加险id',
                'chengbaorule':'承保规则',
                'hebaorule':'核保规则',
                'insurancerule':'保险条款',
                'otherrule':'其他规则',
                'sysrecord':'系统记录',
                'sysproduce':'系统生成',
                'existcheck':'存在性审核',
                'okcheck':'正确性审核',
                'FFcheck':'FF系统校验',
                'yingxiangcheck':'投保单影像校验',
                'checkstandard':'校验标准',
                'remarks':'备注',
                'versionid':'版本号',
                'elementname':'要素名称',
                'percent':88   //80以下标黄  
            }
        ]
        
    },
    methods:{
        //鼠标移上菜单变色
        choose(index){
            if(this.flag2 == index){
                this.flag2 = "10000"
            }else{
                this.flag2 = index
            }
            
        },
        //显示按钮
        showButtons(){
            if(this.flag3 == true){
                this.flag3 = false
            }else{
                this.flag3 = true
            }
        },
        //修改按钮触发的函数
        edit(){
            if(this.flag4 == true){
                this.flag4 = false
            }else{
                this.flag4 = true
            }
        },
        //搜索
        search(e){
            if(e.keyCode == 13){
                  alert('发送搜索内容是'+this.searchContent+'！')
            }
        },
        //新增模块
        showAddM(){

        }
    
    }
})